### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce/vc-module-customer#1]
Special characters !#$%&'*+-/=?^_`{|}~ are allowed in local part of the email. So the email address validation should be improved.

More info [here](https://en.wikipedia.org/wiki/Email_address)

**Comment by eMazeika** [comment]
thanks for the "more info" link. According to it, these characters are valid. Where do you find bug in this case?

**Comment by aartiomov** [comment]
They are not allowed in current VC email validation implementation. Try to save email for a customer with those chars in VC admin.
