### ISSUE TITLE
Region field in the addresses section of the contact should be auto populate dropdown instead of textbox

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-module-customer#146]
Add new address blade in the contacts section should have **Region** as a dropdown which should be populate based on the country selected instead of textbox. This will maintain consistency in region name. This is already there in storefront when user selects country and region name populates based on the country selected.

As the user needs to write region as text, the RegionId is NULL inside the DB.

![image](https://user-images.githubusercontent.com/71070755/119256330-d293cc00-bbdd-11eb-913b-6e981c7fb66e.png)

![image](https://user-images.githubusercontent.com/71070755/119256372-053dc480-bbde-11eb-96cc-e06dc6a290d8.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7423 has been created

**Comment by OlegoO** [comment]
@shubhamdhanetia We are preparing a user story for this feature and I will back with the expected delivery date.

**Comment by shubhamdhanetia** [comment]
Thanks @OlegoO

**Comment by shubhamdhanetia** [comment]
Hi @OlegoO, is there any update?

**Comment by OlegoO** [comment]
@shubhamdhanetia In this sprint - till 11 June, we are improving Country Localization
We are planning to implement your request in the next sprint: 14-25 June. 

I will inform you about the progress.

**Comment by OlegoO** [comment]
@shubhamdhanetia 
Released in https://www.virtocommerce.org/t/news-digest-28-june-2021/349

**Comment by shubhamdhanetia** [comment]
Thanks, @OlegoO !

**Comment by shubhamdhanetia** [comment]
Hello @OlegoO,

I am still seeing the same issue.
How we can get these updates as there is no new release in 'vc module customer' module?

![image](https://user-images.githubusercontent.com/71070755/123758666-ca196a00-d8dc-11eb-8dd5-f83ed1653576.png)

**Comment by OlegoO** [comment]
Sorry, please update the platform, Countries and Regions are Core.
https://github.com/VirtoCommerce/vc-platform/releases/tag/3.67.0

**Comment by shubhamdhanetia** [comment]
Hello @OlegoO , I have updated the platform to 3.67 and reinstalled all the modules.
Then in the platform configuration, I have added countries and countries region json location.
But there is no new release in the Contacts module. So, I am not getting dropdown in region field when I select any country.

**Comment by Vectorfield4** [comment]
Hi, @shubhamdhanetia! You need to update the core module to the 3.17 version. 
Here is a link for you: https://github.com/VirtoCommerce/vc-module-core/releases/tag/3.17.0 
Feel free to ask any questions :)

**Comment by shubhamdhanetia** [comment]
Hello @Vectorfield4, I am not able to open the link. It is giving a 404 error.
Why I am not able to see 3.18 in the Updates section of modules?
Just to know, since the 'Add Address' section is part of vc module customer, are there no changes in this particular module ?

**Comment by shubhamdhanetia** [comment]
I have checked again. I am now able to open the link and I have updated the module.
The issue is fixed and now I am getting regions as dropdowns.
