### ISSUE TITLE
Add support of Assets for Member

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-customer#23]
In B2B it's an often scenario when customer or organization must see documents uploaded for them from admin. Please, add support of assets for member entity and make the Assets widget in admin site like Assets widget for product.

**Comment by eMazeika** [comment]
superseded by https://github.com/VirtoCommerce/vc-platform/issues/1308

**Comment by asvishnyakov** [comment]
@eMazeika @tatarincev AssetEntries is only backend of this feature, UI should be applied to (but not required from client currently, so it has low priority)

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
