### ISSUE TITLE
Update Member.Id with value after adding new member

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-module-customer#25]
Hi,  
Consider the scenario where you add a member and then using observers you want to run actions based on newly added member. 
Member object passed as parameter to MemberChangingEvent has no Id assigned. 

I would expect to receive an Id of just added item to run actions based on that Id. 

Thank you.

**Comment by danielstarzewski** [comment]
Maybe It would be better to add another publisher which would publish **MemberChangedEvent**. Similar to saving orders.

**Comment by tatarincev** [comment]
Yes, definitely need the two events Before, After is  a classic :)

**Comment by danielstarzewski** [comment]
I can do a PR with this. This is not a problem. But to be able to do it I need your approval for a small change adding new event in Core module. Please take a look.
Thanks

**Comment by tatarincev** [comment]
@danielstarzewski  Thanks for the contribution, I've merged your PR into dev branch, on Monday I'll try to release Core module with this change

**Comment by danielstarzewski** [comment]
Thanks. I will continue working on this one on Monday then :)

**Comment by danielstarzewski** [comment]
@tatarincev thanks for quick merge and release. I really appreciate that!
I am now happy to close this issue.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-customer/releases/tag/v2.14.13
