### ISSUE TITLE
Make members list grid extendable

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-customer#3]
I want to add custom columns to the members list grid.
The [documentation ](https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/extend-ui-grid-editable) says there should be an ID for the grid but there is none:
https://github.com/VirtoCommerce/vc-module-customer/blob/master/VirtoCommerce.CustomerModule.Web/Scripts/blades/member-list.tpl.html#L17

**Comment by tatarincev** [comment]
See article: 
https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/extend-ui-grid-editable

**Comment by megafreeman** [comment]
Done https://github.com/VirtoCommerce/vc-module-customer/commit/583ad0de5ead3d3cb55221babaf33440c6cb891c

**Comment by megafreeman** [comment]
@artem-dudarev could you check please, and I'll do a release with this fix.

**Comment by megafreeman** [comment]
Released in [v2.14.6](https://github.com/VirtoCommerce/vc-module-customer/releases/tag/v2.14.6)
