### ISSUE TITLE
Bug with indexation process when dynamic property value is empty

### ISSUE THREAD

**Issue by alex765022** [VirtoCommerce/vc-module-customer#50]
The indexation problem occurs by full rebuild index process when the first indexed item has no values for the dynamic property.

![image](https://user-images.githubusercontent.com/7644848/52846416-37644000-3112-11e9-9ed1-fe5a6b034ff6.png)

Customer management module: 2.14.20
Elasticsearch module: 1.1.2

**Comment by yecli** [comment]
Was released long time ago in https://github.com/VirtoCommerce/vc-module-customer/releases/tag/v2.14.21
