### ISSUE TITLE
Add UserGroup inheritance from parent organization

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-customer#58]
When parent organization has user groups all  contacts belongs to this organization must inherited that user groups if not have self groups assigned.

**Comment by artem-dudarev** [comment]
I think child user groups should be combined with parent users groups, not override them.

**Comment by yecli** [comment]
After some research found that group inheritance implementation would require model changes (for own and inherited group differentiation - we need to distinguish them on save), which could lead to backward compatibility problems.
As a possible solution, inherited group list could be built on storefront.

**Comment by artem-dudarev** [comment]
That's right. We combine all users groups on storefront.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
