### ISSUE TITLE
Vendors and user account association

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-customer#6]
@Skrypt commented on [Fri Oct 07 2016](https://github.com/VirtoCommerce/vc-platform/issues/644)

This is more a question than anything else. I know that Vendors are associated to the Member table in Virto but maybe that would be usefull to be able to associate Vendors with user accounts. 

---

@Woland2k commented on [Fri Oct 07 2016](https://github.com/VirtoCommerce/vc-platform/issues/644#issuecomment-252123327)

It looks like vendor doesn't have accounts associated with it, which is odd. You should be able to associate account with a vendor. It might be a matter of quick extension. @tatarincev why is there no accounts for vendor type? 

---

@Skrypt commented on [Fri Oct 07 2016](https://github.com/VirtoCommerce/vc-platform/issues/644#issuecomment-252124431)

From what I understand Vendors are "Tenants" but I thought that if they are Contacts too they should maybe be associated with accounts. Though, quick ugly way is to link the Vendor email to a User account email.

---

@Woland2k commented on [Fri Oct 07 2016](https://github.com/VirtoCommerce/vc-platform/issues/644#issuecomment-252124546)

Yeah, I believe it was specifically removed as feature for vendor. Probably just a UI element.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
