### ISSUE TITLE
Error when trying to manage any contact via context menu

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-customer#83]
1. Go to Main menu > Contacts
2. Open the context menu by right-clicking on a contact or by clicking on three vertical dots
3. Select Manage

Expected result: contact details blade should open
Actual result: **JS error: Cannot read property 'id' of undefined**
![image](https://user-images.githubusercontent.com/8775253/77678742-47e41c80-6f9a-11ea-99d5-972f5c479aec.png)

The Delete option from the context menu also doesn't work

To open the contact details you can just click on a contact but this is not an option for organizations, so this is a critical bug.

Platform: 2.13.61
VirtoCommerce.Customer: 2.14.25
Browser: Google Chrome 80.0.3987.149 (Official Build) (64-bit)

**Comment by akak1977** [comment]
Repaired. In testing. Will released soon.

**Comment by akak1977** [comment]
Released
https://github.com/VirtoCommerce/vc-module-customer/releases/tag/v2.14.26
